[project]
name = "pac-bdd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Philippe ENTZMANN", email = "philippe@entzmann.name" }
]
requires-python = ">=3.13"
dependencies = [
    "pac0",
]

[dependency-groups]
dev = [
    "nats-server",
    "pytest>=8.0.2",
    "pytest-bdd>=8.1.0",
    "pytest-asyncio>=1.3.0",
    "pytest-html>=4.1.1",
    "pytest-md-report>=0.7.0",
]

[project.scripts]
pac-bdd = "pac_bdd:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
#asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"


[tool.uv.workspace]
members = [
    "../pac0",
]


[tool.uv.sources.pac0]
workspace = true

