[project]
name = "pac-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Philippe ENTZMANN", email = "philippe.entzmann@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
pac-py = "pac_py:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"
