[project]
name = "pac-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Philippe ENTZMANN", email = "philippe.entzmann@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
]

[project.scripts]
pac-py = "pac_py:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "nats-server",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
]


[tool.pytest.ini_options]
#asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"

[tool.uv.sources]
nats-server = { git = "https://github.com/nats-io/nats.py", subdirectory = "nats-server" }
